[workspace]
members = [
    'sixtyfps_runtime/corelib',
    'sixtyfps_runtime/rendering_backends/gl',
    'sixtyfps_compiler',
    'sixtyfps_compiler/parser_test_macro',
    'api/sixtyfps-rs',
    'api/sixtyfps-rs/sixtyfps-rs-macro',
    'tools/viewer',
    'tools/wasm-compiler',
    'examples/graphicstest',
    'examples/rusttest',
    'examples/rustwasmtest',
    'helper_crates/const-field-offset',
    'helper_crates/vtable',
]
