[package]
name = "gl"
version = "0.1.0"
authors = ["Sixty FPS <info@sixtyfps.io>"]
edition = "2018"

[lib]
path = "lib.rs"
crate-type = ["lib", "cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cbindgen = "0.14.2"

[dependencies]
sixtyfps_corelib = { package = "corelib", path = "../../corelib" }
lyon = { version = "0.15.8" }
image = { version = "0.23.4", default-features = false }
cgmath = "0.17.0"
vtable = { path = "../../../helper_crates/vtable" }
font-kit = "0.7.0"
pathfinder_geometry = "0.5.1"
guillotiere = "0.5.1"
itertools = "0.9.0"
harfbuzz = "0.3.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web_sys = { version = "0.3", package = "web-sys", features=["console"] }
wasm-bindgen = { version = "0.2" }
winit = { version = "0.22.1", features = ["web-sys"] }
glow = { version = "0.4.0", default-features = false, features = ["web-sys"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
winit = "0.22.1"
glutin = { version = "0.24" }
glow = { version = "0.4.0", default-features = false }
